icon: ':simple-nextcloud:'
cit:
  mode: screenshot
  port: 8082
  wait: 60
build:
  pkg_name: nextcloud-php83
  variants:
    - tag: pkg
      containerfile: Containerfile.pkg
      aliases: ["latest"]
      default: true
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
